# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.account:
    class: AppBundle\Service\AccountService
    arguments: ['@doctrine']
  app.authentication:
    class: AppBundle\Service\AuthenticationService
    arguments: ['@app.account', '@session']
  app.session:
    class: AppBundle\Service\SessionService
    arguments: ['@session']